---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
    run_list:
      - recipe[apt::default]
  - name: debian-7.8
    run_list:
      - recipe[apt::default]
  - name: centos-7.0

suites:
  - name: default
    run_list:
      - recipe[maxscale::default]
    attributes:
      maxscale:
        databag:
          enabled: true
        config:
          maxscale:
            threads: 2
          MySQL Monitor:
            type: 'monitor'
            module: 'mysqlmon'
            servers: 'server1,server2,server3'
            user: 'myuser'
            passwd: 'mypwd'
            monitor_interval: 10000
          qla:
            type: 'filter'
            module: 'qlafilter'
            options: '/tmp/QueryLog'
          server1:
            type: 'server'
            address: '127.0.0.1'
            port: 3306
            protocol: 'MySQLBackend'
          server2:
            type: 'server'
            address: '127.0.0.2'
            port: 3306
            protocol: 'MySQLBackend'
          Read Connection Router:
            type: 'service'
            router: 'readconnroute'
            servers: 'server1,server2,server3'
            user: 'myuser'
            passwd: 'mypwd'
            router_options: 'slave'
          RW Split Router:
            type: 'service'
            router: 'readwritesplit'
            servers: 'server1,server2,server3'
            user: 'myuser'
            passwd: 'mypwd'
          Read Connection Listener:
            type: 'listener'
            service: 'Read Connection Router'
            protocol: 'MySQLClient'
            address: '127.0.0.4'
            port: '4008'
          RW Split Listener:
            type: 'listener'
            service: 'RW Split Router'
            protocol: 'MySQLClient'
            port: '4006'
